### ISSUE TITLE
Moving Aerocube-ImP within Aerocube

### ISSUE THREAD

**Issue by andrewtran1995** [UCSB-CS189-2016-17-Aerospace/Aerocube#10]
Because of how imports are currently done within the Aerocube directory, there is the implicit requirement that Aerocube-ImP should be nested inside of the Aerocube directory.

Would it be beneficial to just move the ImP repository into the Aerocube repository?

**Comment by GusAlejandro** [comment]
At first glance this seems like a good move. It also clearly separates what is on the jetson and what isn't. I'll think about it but it seems like a solid move.

**Comment by andrewtran1995** [comment]
Okay -- @elswenson, what do you think of this?
